Update README.md
os-js/manual.os-js.org pull request #29
Opened 2020-07-13 11:29 UTC by miladhashemi

Add adapter github address in README.md

2020-07-13 12:02 UTC, andersevenrud requested changes
Also, update the commit message to reflect what was changed, not where.

2020-07-13 12:02 UTC, andersevenrud commented on src/v3/resource/contrib/README.md
> +* https://github.com/BurnaSmartLab/osjs-monster-adapter - An Adapter for os.js to work with swift saio object storage.
Reword this to something like: `Swift saio object storage VFS adapter`

2020-07-14 02:33 UTC, miladhashemi reviewed
Description changed to "Swift saio object storage VFS adapter"

2020-07-14 08:29 UTC, miladhashemi reviewed
Description updated.

2020-07-14 09:38 UTC, andersevenrud commented
I'll just fix the commit message myself. I have to squash the commits anyways.

2020-07-14 09:38 UTC, andersevenrud approved these changes

2020-07-14 09:39 UTC, merged

2020-07-14 09:39 UTC, andersevenrud commented
Thanks!

For reference, this is how I described the commit: https://github.com/os-js/manual.os-js.org/commit/40c3c4a2089b762c5d258c3fa4bcb0ee968569c8

2020-07-14 16:30 UTC, miladhashemi commented
> Thanks!
> 
> For reference, this is how I described the commit: [40c3c4a](https://github.com/os-js/manual.os-js.org/commit/40c3c4a2089b762c5d258c3fa4bcb0ee968569c8)

Your welcome

Yes It's really better commit message! Certainly I will follow your commit message for my later commits.
Thanks!